// flow-typed signature: 157716b3a71397364809b28da15a84fa
// flow-typed version: <<STUB>>/omit-deep_v^0.3.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'omit-deep'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'omit-deep' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'omit-deep/index' {
  declare module.exports: $Exports<'omit-deep'>;
}
declare module 'omit-deep/index.js' {
  declare module.exports: $Exports<'omit-deep'>;
}
