// flow-typed signature: 386591de623de39e36105215dc565855
// flow-typed version: <<STUB>>/upath_v^1.1.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'upath'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'upath' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'upath/build/code/upath' {
  declare module.exports: any;
}

// Filename aliases
declare module 'upath/build/code/upath.js' {
  declare module.exports: $Exports<'upath/build/code/upath'>;
}
