version:  2.1

executors:
  node:
    docker:
      - image: circleci/node:10

commands:
  install_dependencies:
    description: Install project dependencies
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  test:
    working_directory: ~/piggy-www
    executor: node
    steps:
      - checkout
      - install_dependencies
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test:ci
  deploy:
    working_directory: ~/piggy-www
    executor: node
    steps:
      - checkout
      - install_dependencies
      - run:
          name: Install AWS CLI
          command: sudo apt-get -y -qq install awscli
      - run:
          name: Create Environment Variable file
          command: |
            # Set Environment Variable
            export REACT_APP_API_URL_TMP=API_URL_$CIRCLE_BRANCH
            export REACT_APP_API_URL=${!REACT_APP_API_URL_TMP}
            echo "Environment variable REACT_APP_API_URL is set to ${REACT_APP_API_URL}"

            # Create .env file
            touch .env
            echo "REACT_APP_API_URL=${REACT_APP_API_URL}" > .env
      - run:
          name: Build
          command: |
            # Output created .env file
            cat .env

            # Start building
            yarn build
      - run:
          name: Deploy build to AWS S3
          command: aws --region $AWS_REGION s3 cp --acl public-read --recursive build s3://s3-www-$(perl -e '$b=shift;print {"master"=>"production",stage=>"staging"}->{$b}||$b' $CIRCLE_BRANCH).joinpiggy.com

workflows:
  version: 2.1
  release:
    jobs:
      - test
      - deploy:
          filters:
             branches:
               only:
                 - master
                 - stage
                 - integration
          requires:
            - test
